### ISSUE TITLE
uapi/drm/gma_drm.h missing or misplaced or incomplete?

### ISSUE THREAD

**Issue by misanthropos** [patjak/xf86-video-gma500#1]
I like to try out gma500 acceleration but can't compile the xf86 driver. After copying gma_drm.h to the include path
I get
drmmode_display.c:1076:9: error: 'GMA_BO_DISPLAY' undeclared (first use

gma_drm.h has just the definition being included...

gma-500-kernel and libdrm worked fine and are installed.

Can you give me hint on this?

**Comment by patjak** [comment]
Hi, it's not really hooked up properly but what you need for xf86-video-gma500 to find is this file:
https://github.com/patjak/drm-gma500/blob/blitter_hacking/include/uapi/drm/gma_drm.h

So make sure you have the blitter_hacking branch checked out on drm-gma500. Also, you don't need the libdrm repo. All the kernel interface code is in xf86-video-gma500 for the time being, but will be moved to libdrm eventually.

With that said, I don't really remember in what state I left everything. I have probably some more patches laying around that I need to push.

**Comment by misanthropos** [comment]
Thanks for your response, Patrick.

Please push your stashes if needed... I was not able to compile the blitter_hack.. the gma500-next did compile fine.

**Comment by patjak** [comment]
I'll have to spend some time sorting out and cleaning up my code. The reason it's been laying around on my box is that I haven't had time to fix it and the benchmarking I've done shows the blitter to be much slower than blitting with the CPU. So in it's current state, it's unfortunately not very usable.

**Comment by alterdaemon** [comment]
I am keeping my fingers crossed!

This driver would bring another live to some still spectacular machines like Sony Vaio X11, which suffers from the poulsbo..

Regards

**Comment by misanthropos** [comment]
I guess there wont be any development anymore.

**Comment by patjak** [comment]
No, it's quite useless at this point :(
